apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-du
  namespace: oai
spec:
  selector:
    matchLabels:
      run: oai-du
  replicas: 1
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: oai-du-net1
      labels:
        app: oai-du
        run: oai-du
    spec:
      nodeName: antenna-worker
      containers:
        - name: oai-du
          volumeMounts:
            - mountPath: /dev/bus/usb
              name: oai-du-usb
            - mountPath: /lib/modules
              name: oai-du-modules
          image: ttsourdinis/oai-build
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["/bin/bash", "-c"]
          args:
          -  export UHD_IMAGES_DIR=/usr/share/uhd/images;
             uhd_usrp_probe;
             sleep 3;
             /openairinterface5g/targets/bin/./lte-softmodem.Rel14 -O /du.conf;
             while true;
             do sleep 30;
             done;
      volumes:
        - name: oai-du-usb
          hostPath:
              path: /dev/bus/usb
        
        - name: oai-du-modules
          hostPath:
              path: /lib/modules
              
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: oai-du-net1
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "br0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.18.205/24",
    "gateway": "192.168.18.1" } ] } }'
    
    
