apiVersion: apps/v1
kind: Deployment
metadata:
  name: wifi-du
  namespace: oai
spec:
  selector:
    matchLabels:
      run: wifi-du
  replicas: 1
  template:
    metadata:
      labels:
        app: wifi-du
        run: wifi-du
    spec:
      hostNetwork: true
      containers:
        - name: wifi-du
          volumeMounts:
            - mountPath: /dev/bus/usb
              name: wifi-du
          image: ttsourdinis/oai-k8s:wifi-du
          imagePullPolicy: Never
          securityContext:
            privileged: true
          command: ["/bin/sh", "-c"]
          args:
          - ifconfig net1 down;
            ip link delete net1;
            ip link add net1 link br0 type macvlan mode bridge;
            ip addr add 192.168.18.204/24 dev net1;
            ip link set net1 up;
            sleep 1;
            pkill hostapd;
            pkill wpa_supplicant;
            pkill -f hostap;
            pkill -f screen;
            ifconfig wlan0 172.16.0.1/24 down;
            ifconfig wlan0 172.16.0.1/24 up;
            ifconfig net1 mtu 1320;
            IFACE=wlan0;
            read MAC </sys/class/net/$IFACE/address;
            cp /root/heterogeneous-cloudran-startup/hostapd_n.conf /root/hostapd_n.conf;
            /usr/bin/nohup hostapd -d /root/hostapd_n.conf > /tmp/hostapd.log 2>&1 &
            sleep 2;
            python -u /root/oai-flexsplit/proto_server_start.py -I wlan0 -P tcp -p 2210 -i 192.168.18.204 -m 192.168.18.203 -a 50000 -b tcp -c e4:ce:8f:56:bb:3a -s ${MAC} -L info> /tmp/wifidu.log;
            while true;
            do sleep 30;
            done;

      volumes:
        - name: wifi-du
          hostPath:
              path: /dev/bus/usb

