#!/usr/bin/env bash

path="/root/app_aware/deployment/"

#echo {\n "insecure-registries" : ["194.177.207.79:5000"]\n} > /etc/docker/daemon.json
#kubectl create secret docker-registry  regcred --docker-server=194.177.207.79:5000 --docker-username=admin --docker-password=password
kubectl create namespace oai
kubectl create -f "${path}oai-volume.yaml"


kubectl apply -f "${path}cassandra.yaml" --validate=false
sleep 5
kubectl apply -f "${path}oai-hss-devel.yaml" --validate=false
sleep 28
kubectl apply -f "${path}oai-mme-devel.yaml" --validate=false
kubectl create -f "${path}flexran-v2.1.1.yaml" --validate=false
sleep 8
kubectl apply -f "${path}oai-spgwc-devel.yaml" --validate=false
sleep 8
kubectl apply -f "${path}oai-spgwu-devel.yaml" --validate=false
sleep 10
kubectl create -f "${path}web-rtc.yaml" --validate=false
kubectl create -f "${path}sipp.yaml" --validate=false
kubectl create -f "${path}web-server.yaml" --validate=false
kubectl create -f "${path}mysql-deployment.yaml" --validate=false
kubectl create -f "${path}oai-cu.yaml" --validate=false
sleep 5
kubectl create -f "${path}oai-du.yaml" --validate=false

