apiVersion: v1
kind: ServiceAccount
metadata:
  name: spgwu-sa
  namespace: oai
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: spgwu-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: spgwu-sa
  namespace: oai
---
apiVersion: v1
data:
  net_ue_ip: 192.168.20.0/24
  pgw_sgi_if: net3
  pgwc_sx_ip: 192.168.2.100
  pgwu_sgi_gw: 192.168.3.101
  sgw_s1u_if: net2
  sgw_sx_if: net1
kind: ConfigMap
metadata:
  name: spgwu-config
  namespace: oai
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oai-spgwu
  name: oai-spgwu
  namespace: oai
spec:
  clusterIP: None
  ports:
  - name: oai-spgwu
    port: 8805
    protocol: UDP
    targetPort: 8805
  - name: s11
    port: 2152
    protocol: UDP
    targetPort: 2152
  selector:
    app: oai-spgwu
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oai-spgwu
  name: oai-spgwu
  namespace: oai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-spgwu
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: spgwu-net1, spgwu-net2, spgwu-net3, spgwu-net4
      labels:
        app: oai-spgwu
    spec:
      nodeName: cloud-worker
      volumes:
        - name: apps-pvc
          persistentVolumeClaim:
            claimName: apps-pvc

      containers:
      - env:
        - name: SGW_S1U_INTERFACE
          valueFrom:
            configMapKeyRef:
              key: sgw_s1u_if
              name: spgwu-config
        - name: SGW_SX_INTERFACE
          valueFrom:
            configMapKeyRef:
              key: sgw_sx_if
              name: spgwu-config
        - name: PGW_SGI_INTERFACE
          valueFrom:
            configMapKeyRef:
              key: pgw_sgi_if
              name: spgwu-config
        - name: NETWORK_UE_IP
          valueFrom:
            configMapKeyRef:
              key: net_ue_ip
              name: spgwu-config
        - name: PGWC_SX_IP_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: pgwc_sx_ip
              name: spgwu-config
        - name: PGWU_SGI_GW
          valueFrom:
            configMapKeyRef:
              key: pgwu_sgi_gw
              name: spgwu-config
        image: ttsourdinis/oai-spgwu
        command: ["/bin/sh", "-c"]
        args:
        - /opt/oai-spgwu/bin/entrypoint.sh ; 
          /usr/bin/sleep 2;  
          /opt/oai-spgwu/bin/spgwu -c /opt/oai-spgwu/etc/spgw_u.conf -o ;
        


        imagePullPolicy: Never
        name: spgwu
        ports:
        - containerPort: 8805
          name: oai-spgwu
        - containerPort: 2152
          name: s11
        securityContext:
          privileged: true

      - command: ["/bin/sh", "-c"]
        args:
        - python3 /app_aware/parser/live_predictor_pp.py;
          while true;
          do sleep 30;
          done;
        image: ttsourdinis/oai-parser
        securityContext:
          privileged: true
        name: predictor
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: "/mnt"
            name: apps-pvc
      
      - command: ["/bin/sh", "-c"]
        args:
        - python3 sniffer.py;
          while true;
          do sleep 30;
          done;
        image: ttsourdinis/oai-parser
        securityContext:
          privileged: true
        name: sniffer
        imagePullPolicy: IfNotPresent
       

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      serviceAccountName: spgwu-sa
      terminationGracePeriodSeconds: 30
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: spgwu-net1
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "br0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.2.101/24",
    "gateway": "192.168.2.1" } ] } }'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: spgwu-net2
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "br0", "ipam": { "type": "static", "addresses": [ { "address": "172.16.2.100/24",
    "gateway": "172.16.2.1" } ] } }'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: spgwu-net3
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "br0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.3.100/24",
    "gateway": "192.168.3.1" } ] } }'

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: spgwu-net4
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "br0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.18.210/24",
    "gateway": "192.168.18.1" } ] } }'


