apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: oai
  labels:
    app: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      name: web-server
      annotations:
        k8s.v1.cni.cncf.io/networks: web-server-net
      labels:
        app: web-server
    spec:
      nodeName: antenna-worker
      containers:
      - name: web-server
        image: ttsourdinis/web-server
        imagePullPolicy: IfNotPresent
        securityContext:
              privileged: true
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c"]
        args:
        - route add -net 192.168.20.0/24 gw 192.168.3.100;
          cd /mnt;
          nginx;
          while true;
          do sleep 30;
          done;

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: web-server-net
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "br0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.3.103/24",
    "gateway": "192.168.3.1" } ] } }'

