apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-rtc
  namespace: oai
spec:
  selector:
    matchLabels:
      run: web-rtc
  replicas: 1
  template:
    metadata:
      name: web-rtc
      annotations:
        k8s.v1.cni.cncf.io/networks: web-rtc-net1
      labels:
        app: web-rtc
        run: web-rtc
    spec:
      nodeName: antenna-worker
      containers:
        - name: web-rtc
          image: ttsourdinis/webrtc
          imagePullPolicy: Never
          securityContext:
              privileged: true
          command: ["/bin/sh", "-c"]
          args:
          - route add -net 192.168.20.0/24 gw 192.168.3.100; 
            cd /app;
            ./webrtc-streamer -C config.json;
            while true;
            do sleep 30;
            done;

---
apiVersion: v1
kind: Service
metadata:
  name: web-rtc-svc
  namespace: oai
spec:
  type: NodePort
  selector:
    app: web-rtc
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8000
      targetPort: 8000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30002


---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: web-rtc-net1
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "br0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.3.101/24",
    "gateway": "192.168.3.1" } ] } }'

