apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: first-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.9, pipelines.kubeflow.org/pipeline_compilation_time: '2021-12-16T17:40:11.990901',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Simple Git Pipeline.",
      "name": "First Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.9}
spec:
  entrypoint: first-pipeline
  templates:
  - name: data-parser
    container:
      args: []
      command: [python3, step1.py, --data, /tmp/outputs/Data/data]
      image: ttsourdinis/oai-parser
    outputs:
      artifacts:
      - {name: data-parser-Data, path: /tmp/outputs/Data/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Data
          Parsing from MySQL Database and exports new DF with time slots", "implementation":
          {"container": {"command": ["python3", "step1.py", "--data", {"outputPath":
          "Data"}], "image": "ttsourdinis/oai-parser"}}, "name": "Data Parser", "outputs":
          [{"description": "Path where data will be stored.", "name": "Data", "type":
          "LocalPath"}]}', pipelines.kubeflow.org/component_ref: '{"digest": "b48aad8fd31b124b80c016d7622f1d2df60b433bb9af748d4ede6638f97edac4",
          "url": "/root/step1.yaml"}'}
  - name: data-pre
    container:
      args: []
      command: [python3, step2.py, --data, /tmp/inputs/Data/data, --out_x, /tmp/outputs/Array_x/data,
        --out_y, /tmp/outputs/Array_y/data]
      image: ttsourdinis/oai-parser
    inputs:
      artifacts:
      - {name: data-parser-Data, path: /tmp/inputs/Data/data}
    outputs:
      parameters:
      - name: data-pre-Array_x
        valueFrom: {path: /tmp/outputs/Array_x/data}
      - name: data-pre-Array_y
        valueFrom: {path: /tmp/outputs/Array_y/data}
      artifacts:
      - {name: data-pre-Array_x, path: /tmp/outputs/Array_x/data}
      - {name: data-pre-Array_y, path: /tmp/outputs/Array_y/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Data
          Preprocessing", "implementation": {"container": {"command": ["python3",
          "step2.py", "--data", {"inputPath": "Data"}, "--out_x", {"outputPath": "Array_x"},
          "--out_y", {"outputPath": "Array_y"}], "image": "ttsourdinis/oai-parser"}},
          "inputs": [{"description": "Path where data is stored.", "name": "Data",
          "type": "LocalPath"}], "name": "Data Pre", "outputs": [{"description": "Path
          where data will be stored.", "name": "Array_x", "type": "LocalPath"}, {"description":
          "Path where data will be stored.", "name": "Array_y", "type": "LocalPath"}]}',
        pipelines.kubeflow.org/component_ref: '{"digest": "f007eca74f88cdd8cc72ab79f50507f59a9b18c4ec7e26bb89d1954c1378e1a3",
          "url": "/root/step2.yaml"}'}
  - name: first-pipeline
    dag:
      tasks:
      - {name: data-parser, template: data-parser}
      - name: data-pre
        template: data-pre
        dependencies: [data-parser]
        arguments:
          artifacts:
          - {name: data-parser-Data, from: '{{tasks.data-parser.outputs.artifacts.data-parser-Data}}'}
      - name: trainer
        template: trainer
        dependencies: [data-pre]
        arguments:
          parameters:
          - {name: data-pre-Array_x, value: '{{tasks.data-pre.outputs.parameters.data-pre-Array_x}}'}
          - {name: data-pre-Array_y, value: '{{tasks.data-pre.outputs.parameters.data-pre-Array_y}}'}
  - name: trainer
    container:
      args: [--data_x, '{{inputs.parameters.data-pre-Array_x}}', --data_y, '{{inputs.parameters.data-pre-Array_y}}']
      command: [python3, step3.py]
      image: ttsourdinis/oai-parser
      volumeMounts:
      - {mountPath: /mnt, name: pvolume-f1bf2abd102a3f44dd0e8bb9bee0b1b1ef3e9301d5710f847e6352c}
    inputs:
      parameters:
      - {name: data-pre-Array_x}
      - {name: data-pre-Array_y}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    volumes:
    - name: pvolume-f1bf2abd102a3f44dd0e8bb9bee0b1b1ef3e9301d5710f847e6352c
      persistentVolumeClaim: {claimName: kubeflow-pvc}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner